### ISSUE TITLE
Segments in Listview

### ISSUE THREAD

**Issue by enes-sakut** [gspd-mobi/SegmentedBarView-Android#3]
I want to use your library in listview but I tried to layout.addview(barview) in listview it does not work.How can I use in listview your View class?

**Comment by pavelkorolevxyz** [comment]
You can add `SegmentedBarView` to `ListView` cell's layout xml like this:
```xml
<mobi.gspd.segmentedbarview.SegmentedBarView
        android:id="@+id/bar_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
/>
```
and use it as any other view on this cell.

If you need to add `SegmentedBarView` programmatically please provide some more inforomation or code example what you want to do and how you trying to do it now.

**Comment by enes-sakut** [comment]
I'm using Multi segmented barview in Linear layout but I does not implement in Listview.I'm creating this chart. @PavelKorolev 
-LinearLayout(mainLayout)
   -SegmentedBarview
-Progressbar(Blue)
![charview](https://user-images.githubusercontent.com/22794798/35805868-8bbf0a1e-0a8e-11e8-9627-ce667f3f182f.png)

**Comment by pavelkorolevxyz** [comment]
Please provide code you have now for both LinearLayout and ListView cases.

**Comment by enes-sakut** [comment]
This is my ITEM.xml 
` <android.support.constraint.ConstraintLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_weight="1">


            <ProgressBar
                android:id="@+id/progressBarStepsItem"
                style="?android:attr/progressBarStyleHorizontal"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_gravity="center"
                android:layout_weight="1"
                android:gravity="right"
                android:max="100"
                android:progress="51"
                android:progressDrawable="@drawable/border_progress_sleep"
                tools:layout_editor_absoluteX="0dp" />

            <LinearLayout
                android:id="@+id/main_layout"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical">

            <kaffed.barview.SegmentedBarView
                android:id="@+id/progressBarTextSunday"
                android:layout_width="0dp"
                android:layout_height="43dp"
                android:layout_marginTop="8dp"
                android:textAlignment="viewStart"

                android:textColor="@color/colorWhite"
                app:layout_constraintEnd_toEndOf="@+id/progressBarStepsItem"
                app:layout_constraintHorizontal_bias="0.0"
                app:layout_constraintStart_toStartOf="@+id/progressBarStepsItem"
                app:layout_constraintTop_toTopOf="parent" />
            </LinearLayout>

        </android.support.constraint.ConstraintLayout>`

and this is my ListAdapter get view Methods
` @NonNull
    @Override
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {


        Item2 item2 = getItem(position);

        View v = convertView;
        if (v == null) {
           LayoutInflater vi;
            vi = LayoutInflater.from(getContext());
            v = vi.inflate(R.layout.activity_main2,null);
        }
        Item2 p = getItem(position);

        if (p != null) {
            LinearLayout mainLayout = (LinearLayout) v.findViewById(R.id.main_layout);
            ProgressBar tt2 = (ProgressBar) v.findViewById(R.id.progressBarStepsItem);
            SegmentedBarView tt3 = (SegmentedBarView) v.findViewById(R.id.progressBarTextSunday);
        }
        return v;
    }`
and I create segments this method 
` private void createBarViewWithManySegments() {
        SegmentedBarView tt3 = new SegmentedBarView(getContext());
        ArrayList<Segment> segments = new ArrayList<>();


        Segment segment2 = new Segment(20f, 50f, "", parseColor("#7492E2"));
        // Segment segment3 = new Segment(50f, 200f, "", Color.parseColor("#EF3D2F"));

        for (int i=0; i<144;i++){

            if (i==1 || i==3 || i==5 || i==7||  i==9|| i==11 || i==6 || i==16|| i==26|| i==36|| i==46|| i==56|| i==66|| i==76 ||i==45|| i==55|| i==65|| i==75 || i==44|| i==54|| i==64|| i==74){

                segment2=new Segment(0f,144f,"",parseColor("#EF3D2F"));
            }
            else
            {
                segment2=new Segment(0f,144f,"",parseColor("#00000000"));
            }
            segments.add(segment2);
        }
        tt3.setBarHeight(40);
        tt3.setGapWidth(0);
        tt3.setSegments(segments);
        tt3.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.WRAP_CONTENT));
        tt3.setPadding(0, 1, 0, 0);
        mainLayout.addView(tt3);
        
    }`
but in listview mainlayout.addview got errors Null Point Exception.

**Comment by pavelkorolevxyz** [comment]
You need to pass segments to your ListView adapter somehow so you can write
```java
SegmentedBarView tt3 = (SegmentedBarView) v.findViewById(R.id.progressBarTextSunday);
tt3.setSegments(segments);
```
in your `getView()` method.

That's how adapters work, it doesn't relate to `SegmentedBarView` in any way. You'll get NullPointerException in any case and with any view just like that. Don't save Views in adapter, just make adapter to get some data which is enough to set everything in right state in `getView()` function.

**Comment by enes-sakut** [comment]
Okkey man thanks a lot))
